num.13

diff --git a/cicd-docker-wordpress-pipeline/Jenkinsfile b/cicd-docker-wordpress-pipeline/Jenkinsfile
--- a/cicd-docker-wordpress-pipeline/Jenkinsfile
+++ b/cicd-docker-wordpress-pipeline/Jenkinsfile
@@ -1,23 +1,68 @@
 pipeline {
     agent any
     
+    environment {
+        DOCKER_HUB_REPO = "bendrorasaf/wordpress"
+        CONTAINER_NAME = "wordpress"
+        IMAGE_NAME = 'wordpress'
+        TAG = "V1.${BUILD_NUMBER}"
+        DOCKERHUB_CREDENTIALS = credentials('docker')
+    }
+ 
     stages {
-        stage('Test') {
+        stage('Checkout') {
             steps {
-                echo 'Hello, World!'
+                checkout scm
+            }
+        }
+    
+        stage('Build Image') {
+            steps {
+                script {
+                    sh "docker build -t ${IMAGE_NAME}:${TAG} ."
+                }
+            }
+        }
+    
+        stage('Test Container') {
+            steps {
+                script {
+                    sh "docker run -d --name ${CONTAINER_NAME} ${IMAGE_NAME}:${TAG}"
+                    sh "docker stop ${CONTAINER_NAME}"
+                    sh "docker rm ${CONTAINER_NAME}"
+                }
+            }
+        }
+    
+        stage("Login to DockerHub") {
+            steps {
+                script {
+                    withCredentials([usernamePassword(credentialsId: 'docker', passwordVariable: 'DOCKERHUB_PSW', usernameVariable: 'DOCKERHUB_USR')]) {
+                        sh "echo \$DOCKERHUB_PSW | docker login -u \$DOCKERHUB_USR --password-stdin"
+                    }
+                }
+            }
+        }
+    
+        stage("Push Image") {
+            steps {
+                sh "docker tag ${IMAGE_NAME}:${TAG} ${DOCKER_HUB_REPO}:${TAG}"
+                sh "docker push ${DOCKER_HUB_REPO}:${TAG}" 
             }
         }
     }
-    
+  
     post {
         always {
-            echo 'This will always run'
+            sh 'docker logout'
+            sh 'docker rmi -f $(docker images -q) || true'
+            echo 'Cleanup completed'
         }
         success {
-            echo 'This will run only if successful'
+            echo "Pipeline executed successfully"
         }
         failure {
-            echo 'This will run only if failed'
+            echo "Pipeline execution failed"
         }
     }
 }
